/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  /usr/bin/gengetopt -i /home/axel/Dokumente/Studium/Semester_7/routing/cmake-build-debug/find_nodes.ggo -F cmdline_find_nodes --output-dir=src/cli 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline_find_nodes.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: find_nodes -g graph_file.graph ...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "outputs all or some randomly selected nodes matching a filter";

const char *gengetopt_args_info_help[] = {
  "  -h, --help              Print help and exit",
  "  -V, --version           Print version and exit",
  "\ninput/output files:",
  "  -g, --graph-file=FILE   path to graph file (of type .fmi or .graph or .gl)",
  "  -o, --output-file=FILE  path to output file",
  "\nselect random:",
  "  -r, --pick-random=INT   number of nodes to pick randomly (from filtered\n                            nodes)",
  "  -s, --seed=INT          seed for selecting random nodes  (default=`0xC0FFEE')",
  "\ncoordinates:",
  "  -x, --minX=DOUBLE       minimal x coordinate (or longitude) of nodes",
  "  -X, --maxX=DOUBLE       maximal x coordinate (or longitude) of nodes",
  "  -y, --minY=DOUBLE       minimal y coordinate (or latitude) of nodes",
  "  -Y, --maxY=DOUBLE       maximal y coordinate (or latitude) of nodes",
  "      --exact             output the node id for (x,y) (and (X,Y) if given)",
  "\ntriangulation:",
  "  -b, --boundary-nodes    only keep boundary nodes  (default=off)",
  "  -c, --connected         only keep nodes that have edges  (default=on)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_DOUBLE
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->graph_file_given = 0 ;
  args_info->output_file_given = 0 ;
  args_info->pick_random_given = 0 ;
  args_info->seed_given = 0 ;
  args_info->minX_given = 0 ;
  args_info->maxX_given = 0 ;
  args_info->minY_given = 0 ;
  args_info->maxY_given = 0 ;
  args_info->exact_given = 0 ;
  args_info->boundary_nodes_given = 0 ;
  args_info->connected_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->graph_file_arg = NULL;
  args_info->graph_file_orig = NULL;
  args_info->output_file_arg = NULL;
  args_info->output_file_orig = NULL;
  args_info->pick_random_orig = NULL;
  args_info->seed_arg = 0xC0FFEE;
  args_info->seed_orig = NULL;
  args_info->minX_orig = NULL;
  args_info->maxX_orig = NULL;
  args_info->minY_orig = NULL;
  args_info->maxY_orig = NULL;
  args_info->boundary_nodes_flag = 0;
  args_info->connected_flag = 1;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->graph_file_help = gengetopt_args_info_help[3] ;
  args_info->output_file_help = gengetopt_args_info_help[4] ;
  args_info->pick_random_help = gengetopt_args_info_help[6] ;
  args_info->seed_help = gengetopt_args_info_help[7] ;
  args_info->minX_help = gengetopt_args_info_help[9] ;
  args_info->maxX_help = gengetopt_args_info_help[10] ;
  args_info->minY_help = gengetopt_args_info_help[11] ;
  args_info->maxY_help = gengetopt_args_info_help[12] ;
  args_info->exact_help = gengetopt_args_info_help[13] ;
  args_info->boundary_nodes_help = gengetopt_args_info_help[15] ;
  args_info->connected_help = gengetopt_args_info_help[16] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->graph_file_arg));
  free_string_field (&(args_info->graph_file_orig));
  free_string_field (&(args_info->output_file_arg));
  free_string_field (&(args_info->output_file_orig));
  free_string_field (&(args_info->pick_random_orig));
  free_string_field (&(args_info->seed_orig));
  free_string_field (&(args_info->minX_orig));
  free_string_field (&(args_info->maxX_orig));
  free_string_field (&(args_info->minY_orig));
  free_string_field (&(args_info->maxY_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->graph_file_given)
    write_into_file(outfile, "graph-file", args_info->graph_file_orig, 0);
  if (args_info->output_file_given)
    write_into_file(outfile, "output-file", args_info->output_file_orig, 0);
  if (args_info->pick_random_given)
    write_into_file(outfile, "pick-random", args_info->pick_random_orig, 0);
  if (args_info->seed_given)
    write_into_file(outfile, "seed", args_info->seed_orig, 0);
  if (args_info->minX_given)
    write_into_file(outfile, "minX", args_info->minX_orig, 0);
  if (args_info->maxX_given)
    write_into_file(outfile, "maxX", args_info->maxX_orig, 0);
  if (args_info->minY_given)
    write_into_file(outfile, "minY", args_info->minY_orig, 0);
  if (args_info->maxY_given)
    write_into_file(outfile, "maxY", args_info->maxY_orig, 0);
  if (args_info->exact_given)
    write_into_file(outfile, "exact", 0, 0 );
  if (args_info->boundary_nodes_given)
    write_into_file(outfile, "boundary-nodes", 0, 0 );
  if (args_info->connected_given)
    write_into_file(outfile, "connected", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->graph_file_given)
    {
      fprintf (stderr, "%s: '--graph-file' ('-g') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  
  /* checks for dependences among options */
  if (args_info->seed_given && ! args_info->pick_random_given)
    {
      fprintf (stderr, "%s: '--seed' ('-s') option depends on option 'pick-random'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  if (args_info->exact_given && ! args_info->maxX_given)
    {
      fprintf (stderr, "%s: '--exact' option depends on option 'maxX'%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "graph-file",	1, NULL, 'g' },
        { "output-file",	1, NULL, 'o' },
        { "pick-random",	1, NULL, 'r' },
        { "seed",	1, NULL, 's' },
        { "minX",	1, NULL, 'x' },
        { "maxX",	1, NULL, 'X' },
        { "minY",	1, NULL, 'y' },
        { "maxY",	1, NULL, 'Y' },
        { "exact",	0, NULL, 0 },
        { "boundary-nodes",	0, NULL, 'b' },
        { "connected",	0, NULL, 'c' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVg:o:r:s:x:X:y:Y:bc", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'g':	/* path to graph file (of type .fmi or .graph or .gl).  */
        
        
          if (update_arg( (void *)&(args_info->graph_file_arg), 
               &(args_info->graph_file_orig), &(args_info->graph_file_given),
              &(local_args_info.graph_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "graph-file", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* path to output file.  */
        
        
          if (update_arg( (void *)&(args_info->output_file_arg), 
               &(args_info->output_file_orig), &(args_info->output_file_given),
              &(local_args_info.output_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output-file", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* number of nodes to pick randomly (from filtered nodes).  */
        
        
          if (update_arg( (void *)&(args_info->pick_random_arg), 
               &(args_info->pick_random_orig), &(args_info->pick_random_given),
              &(local_args_info.pick_random_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "pick-random", 'r',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* seed for selecting random nodes.  */
        
        
          if (update_arg( (void *)&(args_info->seed_arg), 
               &(args_info->seed_orig), &(args_info->seed_given),
              &(local_args_info.seed_given), optarg, 0, "0xC0FFEE", ARG_INT,
              check_ambiguity, override, 0, 0,
              "seed", 's',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* minimal x coordinate (or longitude) of nodes.  */
        
        
          if (update_arg( (void *)&(args_info->minX_arg), 
               &(args_info->minX_orig), &(args_info->minX_given),
              &(local_args_info.minX_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "minX", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'X':	/* maximal x coordinate (or longitude) of nodes.  */
        
        
          if (update_arg( (void *)&(args_info->maxX_arg), 
               &(args_info->maxX_orig), &(args_info->maxX_given),
              &(local_args_info.maxX_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "maxX", 'X',
              additional_error))
            goto failure;
        
          break;
        case 'y':	/* minimal y coordinate (or latitude) of nodes.  */
        
        
          if (update_arg( (void *)&(args_info->minY_arg), 
               &(args_info->minY_orig), &(args_info->minY_given),
              &(local_args_info.minY_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "minY", 'y',
              additional_error))
            goto failure;
        
          break;
        case 'Y':	/* maximal y coordinate (or latitude) of nodes.  */
        
        
          if (update_arg( (void *)&(args_info->maxY_arg), 
               &(args_info->maxY_orig), &(args_info->maxY_given),
              &(local_args_info.maxY_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "maxY", 'Y',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* only keep boundary nodes.  */
        
        
          if (update_arg((void *)&(args_info->boundary_nodes_flag), 0, &(args_info->boundary_nodes_given),
              &(local_args_info.boundary_nodes_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "boundary-nodes", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* only keep nodes that have edges.  */
        
        
          if (update_arg((void *)&(args_info->connected_flag), 0, &(args_info->connected_given),
              &(local_args_info.connected_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "connected", 'c',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* output the node id for (x,y) (and (X,Y) if given).  */
          if (strcmp (long_options[option_index].name, "exact") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->exact_given),
                &(local_args_info.exact_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "exact", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
